name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: homebots/workflows/.github/workflows/docker-build-and-push.yml@master
    with:
      registry: ghcr.io
      org: ghcr.io/homebots
      defaultBranch: main
      imageName: xtensa-gcc
      platforms: linux/amd64
    secrets:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}

  self-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          mkdir -m a+w -p firmware build
          ls -al
          docker run --rm -u 1000:1000 -v $GITHUB_WORKSPACE:/home/project:rw ghcr.io/homebots/xtensa-gcc:${{github.sha}} make
          ls -al firmware/
