name: CICD

on: [push]

jobs:
  build:
    uses: homebots/workflows/.github/workflows/docker-build-and-push.yml@master
    with:
      org: homebotz
      imageName: xtensa-gcc
    secrets:
      username: ${{ secrets.DOCKER_HUB_USERNAME }}
      password: ${{ secrets.DOCKER_HUB_TOKEN }}

  self-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - run: docker run --rm -v $GITHUB_WORKSPACE:/home/project homebotz/xtensa-gcc make
